theme: jekyll-theme-cayman
title: Linux Server Setup Scripts
description: Automated deployment for Web, Database, and DNS servers
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme